name: Python test
on: [workflow_dispatch]
#on:
#  push:
#    branches: [ $default-branch ]
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.6]
        #exclude:
        #  - os: windows-latest
        #    python-version: 3.6
    steps:
      - name: update pip
        run: pip install --upgrade pip
      - name: load libs
        run: pip install -r requirements.txt
      - name: show dir
        run: dir
      - name: build
        run: pyinstaller --distpath ./ -F oscTest.py
    #  - name: build
    #    run: compile.bat