name: test python version gathering
on: [workflow_dispatch]
jobs:
  check-version:
    runs-on: windows-latest
    steps:
      - name: Set up Python 3.6.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.6.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x86'
      - name: Retrieve python version
        id: py
        run: echo "::set-output name=version::$(python -c 'import sys;print(sys.version.split()[0]);')"
      - name: print version
        run: echo "${{ steps.py.outputs.version }}"
